### ISSUE TITLE
Doesn't do anything?

### ISSUE THREAD

**Issue by Vash115** [topher-au/HDT-Voice#1]
basically that, windows Voice recognisition software works fine, but when i get into hearthstone and speak nothing happends. Am i doing something wrong? . I did pretty much all you said.

**Comment by topher-au** [comment]
Hi,

Can you tell me which version of Windows you are running, which Speech Recognition Engines you have installed, and perhaps send me the debug logfile (enable in settings) which may shed some light.

**Comment by Vash115** [comment]
Actually, i lowered the treshold and it started working , not too well tho. It ended my turn 2 times in a row  and had to restart hearthstone to turn it off :( there should be like a confirmation when you want to end your turn, else it can really screw you over (really, it should confirm most actions, a "yes" or "no" should be fine!). Else, it won't be worth risking loosing your games for it :( .

**Comment by topher-au** [comment]
I'd suggest you check your microphone positioning or switch to push to talk mode.
