### ISSUE TITLE
Next HDT Update

### ISSUE THREAD

**Issue by azeier** [topher-au/HDT-Voice#2]
The next HDT update will most likely require some (minor) changes for your plugin to properly work.

See here for more info and a pre-release download: https://github.com/Epix37/HDT-Test/releases/tag/v0.10.12PRE3

**Comment by azeier** [comment]
Fixed a problem where the GameV2 instance was not accessible, please download the latest pre-release here: https://github.com/Epix37/HDT-Test/releases

**Note:** You plugin will no doubt still "run" with this version but `Hearthstone.Game.cs` **is no longer used** and any references to it need to be changed to `API.Core.Game`.

**Comment by topher-au** [comment]
Hello! Thanks for the notification, I noticed Collection Tracker had been
updated and was just looking into it. I'm onto it, thanks!

On Mon, Aug 24, 2015 at 1:17 AM, Epix notifications@github.com wrote:

> Fixed a problem where the GameV2 instance was not accessible, please
> download the latest pre-release here:
> https://github.com/Epix37/HDT-Test/releases
> 
> _Note:_ You plugin will no doubt still "run" with this version but
> Hearthstone.Game.cs _is no longer used_ and any references to it need to
> be changed to API.Core.Game.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/topher-au/HDT-Voice/issues/2#issuecomment-133861057.

## 

Thankyou,
Chris Sheridan lordramza@gmail.com

**Comment by topher-au** [comment]
Fixes applied in version 0.7 pre-release 1
