### ISSUE TITLE
Zip included in version 8.3 release leads to 8.1

### ISSUE THREAD

**Issue by judge2020** [topher-au/HDT-Voice#5]
When running the 8.3 dll with HDT, it throws an exception and states that the plugin is version 8.1.

**Comment by SoreThumb1** [comment]
This is true. Getting this error

![image](https://cloud.githubusercontent.com/assets/25835158/23335242/e52847d4-fb65-11e6-93a5-d473134cad87.png)

**Comment by judge2020** [comment]
Hey @SoreThumb1, this is the old repo and the plugin will not work. Since the creator abandoned it, the community has started maintaining it: https://github.com/HearthSim/HDT-Voice

Please note that it is still buggy, however it will work.
